import {test,expect} from "@playwright/test";
import { exec } from "child_process";
import exp from "constants";
import { openAsBlob } from "fs";

test("verify Jumbo Mortgages page", async({page})=>{
    await page.goto("https://www.carlylefinancial.com/");
    //await expect(page.url()).toBe("https://www.carlylefinancial.com/");
    await expect(page.locator("//li[@id='menu-item-21044']//a[contains(text(),'Services')]")).hover();
    //await expect(page.locator("ul>li")).toContainText(['Jumbo Mortgages', 'Buying A Home', 'Mortgage Refinance', 'Investment Properties']);
    //await expect(page.locator("ul>li")).toContainText(['Our Calculators', 'Amortization', 'Mortgage', 'Loan Comparison', 'Refinance']);
    await page.locator("//li[@id='menu-item-2560']//a[normalize-space()='Jumbo Mortgages']").click();
    await expect(page.url()).toBe("https://www.carlylefinancial.com/jumbo-mortgages/");
    await expect(page.locator("//h1[normalize-space()='Jumbo Mortgages']")).toHaveText("Jumbo Mortgages");
    await expect(page.locator("//h3[normalize-space()='Experience the Service You Deserve']")).toBeVisible();
    await expect(page.locator("//h2[normalize-space()='Loan Details']")).toBeVisible();
    await expect(page.locator("//li[@id='field_11_3']")).toBeVisible();
    //await page.locator("//span[normalize-space()='Select']").click();
    //await expect(page.locator("ul>li")).toContainText(['Select','to buy a home','to refinance my current loan balance','to refinance and take cash out','to get a second opinion(I have a loan elsewhere)','to discuss something non-mortgage related']);
    //await page.locator("//li[normalize-space()='to buy a home']").click();
    //await page.locator("//div[@id='input_11_52_chosen']//span[contains(text(),'Select')]").click();
    //await expect(page.locator("ul>li")).toContainText(['Select','Single Family Residence','Condo','PUD','Duplex','4-plex']);
    //await page.locator("//li[normalize-space()='Condo']").click();
    //await page.locator("//div[@id='input_11_51_chosen']//span[contains(text(),'Select')]").click();
    //await expect(page.locator("ul>li")).toContainText(['Select','Primary Property','Second Home','Investment Property']);
    //await page.locator("//li[normalize-space()='Second Home']").click();
    //await page.locator("//div[@id='input_11_53_chosen']//span[contains(text(),'Select')]").click();
    //await expect(page.locator("ul>li")).toContainText(['Select','780+ FICO','760-779','740-759','720-739','700-719','680-699','660-679',"Not Sure/Don't Know"]);
    //await page.locator("//li[normalize-space()='760-779']").click();
    //await page.locator("//input[@id='input_11_25']").fill('7098');
    //await page.locator("//input[@id='input_11_22']").fill('8907');
    //await expect(page.locator("//h2[normalize-space()='Personal Information']")).toBeVisible();
    //await page.locator("//input[@id='input_11_29']").fill('Ben');
    //await(page.locator("//input[@id='input_11_5']")).fill('max');
    //await page.locator("//input[@id='input_11_30']").fill('2345678900');
    //await page.locator("//input[@id='input_11_34']").fill('we@gmail.com');
    //await page.locator("//select[@id='input_11_41']").click();
    //await page.locator("//option[@value='Alpine County']").click();
    await expect(page.locator("//b[contains(text(),'Super Jumbo Home Loans – An Overview')]")).toHaveText("Super Jumbo Home Loans – An Overview");
    await expect(page.locator("//b[normalize-space()='Interest Only Jumbo Home Loans']")).toHaveText("Interest Only Jumbo Home Loans");
    await expect(page.locator("//strong[normalize-space()='Do You Need a Jumbo Mortgage?']")).toHaveText("Do You Need a Jumbo Mortgage?");
    await expect(page.locator("//strong[normalize-space()='What Do You Do Next?']")).toHaveText("What Do You Do Next?");
    //await expect(page.locator("//div[@class='form-footer']")).toContainText(['No Obligation','No Obligation','No Obligation']);
    await page.locator("//span[normalize-space()='help employees using RSU income']").click();
    await expect(page.locator("https://www.carlylefinancial.com/blog/rsu-mortgage-from-use-restricted-stock-units-buy-home/"));
    await expect(page.locator("//h1[normalize-space()='Do RSUs Count As Income For a Home Loan in 2024?']")).toHaveText("Do RSUs Count As Income For a Home Loan in 2024?");
    await expect(page.locator("(//h2[@class='simpletoc-title'][normalize-space()='Table of Contents'])[1]")).toHaveText("Table of Contents");
    await expect(page.locator("//h2[@id='aioseo-what-are-restricted-stock-units']")).toHaveText("What are Restricted Stock Units?");
    await expect(page.locator("//h2[@id='aioseo-can-rsus-be-used-as-income-for-a-home-loan']").toHaveText("Can RSUs be used as income for a home loan?"));
    await expect(page.locator("(//h2[contains(text(),'How can you use vested income to qualify for a mor')])[1]")).toHaveText("How can you use vested income to qualify for a mortgage?");
    await expect(page.locator("//h4[normalize-space()='Robert Cohan']")).toHaveText("Robert Cohan");
    await expect(page.locator("//div[@class='staff-meta-item position']//*[name()='svg']")).toHaveText(" President");
    await expect(page.locator("//div[@class='staff-meta-item location']")).toHaveText(" San Francisco");
    await expect(page.locator("//div[@class='staff-meta-item contact']")).toHaveText(" Message");
    await exepect(page.locator("ul>li")).toContainText("Robert’s Blogs","About");
    await page.locator("//a[contains(text(),'Robert’s Blogs')]").click();
    await expect(page.locator("(//div[@id='panel1'])[1]")).toBeVisible();
    await page.locator("//a[normalize-space()='About']").click();
    await expect(page.locator("//div[@class='tabs-content']")).toBeVisible();
    await page.goBack();
    await expect(page.url()).toBe("https://www.carlylefinancial.com/jumbo-mortgages/");
    await page.locator("//a[contains(text(),'get in touch with one of our mortgage experts toda')]").click();
    await expect(page.url()).toBe("https://www.carlylefinancial.com/get-started/");
    await expect(page.locator("//h2[normalize-space()='My Loan Details']")).toHaveText('My Loan Details');
    // await expect(page.locator("ul>li")).toContainText(['Loan Purpose','Occupancy','Credit Score','Property Type','Desired Loan Amount ($)']);
    // await page.locator("//div[@id='input_15_2_chosen']").click();
    // await expect(page.locator("ul>li")).toContainText(['- Select One -','Purchase','Pre-Approval','Refinance','Refinance (Cash-Out)']);
    // await page.locator("(//li[normalize-space()='Pre-Approval'])[1]").click();
    // await page.locator("//div[@id='input_15_70_chosen']").click();
    // await expect(page.locator("Ul>li")).toContainText(['Primary Property','Second Home','Investment Property']);
    // await page.locator("//li[normalize-space()='Second Home']").click();
    // await page.locator("//div[@id='input_15_69_chosen']").click();
    // await expect(page.locator("ul>li")).toContainText(['- Select One -','780+ FICO','760-779','740-759','720-739','700-719','680-699','660-679',"Not Sure/Don't Know"]);
    // await page.locator("//li[normalize-space()='760-779']").click();
    // await page.locator("//div[@id='input_15_71_chosen']").click();
    // await expect(page.locator("ul>li")).toContainText(['- Select One -','Single Family Residence','Condo','PUD','Duplex','4-plex']);
    // await page.locator("//li[normalize-space()='Duplex']").click();
    // await page.locator("//input[@id='input_15_48']").fill('530');
    // await page.locator("//input[@id='input_15_51']").fill('531');
    // await expect(page.locator("//h2[normalize-space()='Contact Information']")).toHaveText('Contact Information');
    // await expect(page.locator("ul>li")).toContainText(['First Name','Last Name','Phone Number','Email Address','Additional Information']);
    // await page.locator("//input[@id='input_15_7']").fill('matt');
    // await page.locator("//input[@id='input_15_8']").fill('pine');
    // await page.locator("//input[@id='input_15_43']").fill('9876543210');
    // await page.locator("//input[@id='input_15_30']").fill('pine@gmail.com');
    // await page.locator("//textarea[@id='input_15_10']").fill('Best time to call');
    // await expect(page.locator("(//span[contains(text(),'No Obligation')])[1]")).toHaveText('No Obligation');
    // await expect(page.locator("(//span[contains(text(),'Secure')])[1]")).toHaveText('Secure');
    // await expect(page.locator("(//span[contains(text(),'Expert Advice')])[1]")).toHaveText('Expert Advice');
    // await page.locator("//input[@id='gform_submit_button_15']").click();
    // await page.waitForTimeout(5000);
    // await expect(page.url()).toBe("https://www.carlylefinancial.com/thank-you-for-contacting-carlyle-financial/#gf_15");
    // await expect(page.locator("//h1[normalize-space()='Thank You']")).toHaveText('Thank You');
    // await expect(page.locator("//a[normalize-space()='Homepage']")).toHaveText('Homepage');
    // await expect(page.locator("//a[normalize-space()='View our Blog']")).toHaveText('View our Blog');
});
